# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jian Du
tagline:             'Blog'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://jiandu.github.io
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Jian Du
  url:               https://jiandu.github.io
  email:             

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]